services:
  blockchain:
    build:
      context: ./Backend
    container_name: traceability-blockchain
    ports:
      - "8545:8545"
    networks:
      - traceability-network
  

  backend:
    build:
      context: ./Backend2
    container_name: traceability-backend
    ports: 
      - "3500:3500"
    env_file:
      - ./Backend2/.env.demo
    depends_on:
      - blockchain
    networks:
      - traceability-network

networks:

  traceability-network:
    driver: bridge